### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by Mybrc91** [feelschaotic/AopAutoTryCatch#2]
Cannot infer Groovy class path because no Groovy Jar was found on class path: configuration ':buildsrc:compileClasspath'

**Comment by feelschaotic** [comment]
你好，是否clean过再重新build？因为使用groovy插件会去src/main/groovy查找源码，需要重新构建项目。

如果仍然不行，可以尝试在buildSrc的build.gradle加入

```
repositories {
   mavenCentral()
}

dependencies {
   compile 'org.codehaus.groovy:groovy:2.3.7'
}
```

**Comment by Mybrc91** [comment]
> 你好，是否clean过再重新build？因为使用groovy插件会去src/main/groovy查找源码，需要重新构建项目。
> 
> 如果仍然不行，可以尝试在buildSrc的build.gradle加入
> 
> ```
> repositories {
>    mavenCentral()
> }
> 
> dependencies {
>    compile 'org.codehaus.groovy:groovy:2.3.7'
> }
> ```
启动崩溃
```java
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.feelschaotic.aopapplication/com.feelschaotic.javassist.MainActivity}: java.lang.ArithmeticException: divide by zero
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ArithmeticException: divide by zero
        at com.feelschaotic.javassist.MainActivity.catchAllException(MainActivity.java:28)
        at com.feelschaotic.javassist.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by feelschaotic** [comment]
`catchAllException()` 方法崩溃，因为PathPlugin插件没有生效，所以没有自动生成catch代码，请检查目录是否有改动是否对应，导致代码无法注入。

```
1. TryCatchInject 的 PROCESSED_ANNOTATION_NAME
2. PathTransform 的 TryCatchInject.injectDir(it.file.absolutePath, "com\\feelschaotic\\javassist")
3. TryCatchInject 的 ctMethod.addCatch('{com.feelschaotic.javassist.Logger.print($e);return;}', etype)
```

**Comment by Mybrc91** [comment]
> PROCESSED_ANNOTATION_NAME
没有改动
```java
1. final String PROCESSED_ANNOTATION_NAME = "com.feelschaotic.javassist.annotations.AutoTryCatch"
2. TryCatchInject.injectDir(it.file.absolutePath, "com\\feelschaotic\\javassist")
3. private static catchAllExceptions(CtMethod ctMethod) {
        CtClass etype = pool.get("java.lang.Exception")
        ctMethod.addCatch('{com.feelschaotic.javassist.Logger.print($e);return;}', etype)
    }

```

**Comment by feelschaotic** [comment]
> > PROCESSED_ANNOTATION_NAME
> > 没有改动
> 
> ```java
> 1. final String PROCESSED_ANNOTATION_NAME = "com.feelschaotic.javassist.annotations.AutoTryCatch"
> 2. TryCatchInject.injectDir(it.file.absolutePath, "com\\feelschaotic\\javassist")
> 3. private static catchAllExceptions(CtMethod ctMethod) {
>         CtClass etype = pool.get("java.lang.Exception")
>         ctMethod.addCatch('{com.feelschaotic.javassist.Logger.print($e);return;}', etype)
>     }
> ```

我的意思不是检查代码里的目录配置是否有改动，是检查项目目录和代码目录是否对应，项目目录是否有改动

**Comment by Mybrc91** [comment]
> > > PROCESSED_ANNOTATION_NAME
> > > 没有改动
> > 
> > 
> > ```java
> > 1. final String PROCESSED_ANNOTATION_NAME = "com.feelschaotic.javassist.annotations.AutoTryCatch"
> > 2. TryCatchInject.injectDir(it.file.absolutePath, "com\\feelschaotic\\javassist")
> > 3. private static catchAllExceptions(CtMethod ctMethod) {
> >         CtClass etype = pool.get("java.lang.Exception")
> >         ctMethod.addCatch('{com.feelschaotic.javassist.Logger.print($e);return;}', etype)
> >     }
> > ```
> 
> 我的意思不是检查代码里的目录配置是否有改动，是检查项目目录和代码目录是否对应，项目目录是否有改动

没有改动。。打开项目就这样

**Comment by feelschaotic** [comment]
> > > > PROCESSED_ANNOTATION_NAME
> > > > 没有改动
> > > 
> > > 
> > > ```java
> > > 1. final String PROCESSED_ANNOTATION_NAME = "com.feelschaotic.javassist.annotations.AutoTryCatch"
> > > 2. TryCatchInject.injectDir(it.file.absolutePath, "com\\feelschaotic\\javassist")
> > > 3. private static catchAllExceptions(CtMethod ctMethod) {
> > >         CtClass etype = pool.get("java.lang.Exception")
> > >         ctMethod.addCatch('{com.feelschaotic.javassist.Logger.print($e);return;}', etype)
> > >     }
> > > ```
> > 
> > 
> > 我的意思不是检查代码里的目录配置是否有改动，是检查项目目录和代码目录是否对应，项目目录是否有改动
> 
> 没有改动。。打开项目就这样

那就是因为PathPlugin插件没有生效。请在 app build.gradle 中找到 `apply plugin: com.feelschaotic.plugin.PathPlugin`，ctrl+点击 PathPlugin，是否正常跳转到 buildSrc 项目的 PathPlugin。如果有正常跳转，可调试 Plugin 查看具体报错，调试方式见：https://www.jianshu.com/p/99c8e953654e

同时留意 Gradle Console 是否有报错信息。

**Comment by Mybrc91** [comment]
> 体报错，

不能跳转

**Comment by feelschaotic** [comment]
> 不能跳转

不能跳转说明完全没有找到PathPlugin插件，你可以
1. 先检查 PathPlugin 的路径是否正确，是否是`com.feelschaotic.plugin.`
2. 路径正常，则先注释掉 `apply plugin: com.feelschaotic.plugin.PathPlugin` 
2. 重新 clean rebuild 确保编译成功
3. 再依次敲入 `apply plugin: com.feelschaotic.plugin.PathPlugin` 留意IDE是否出现键入提示，如图：

![](https://user-images.githubusercontent.com/23227460/54605850-344bcf00-4a85-11e9-9107-0be7304e7e5f.png)

如果没有出现键入提示，且上面步骤后还是找不到`com.feelschaotic.plugin.PathPlugin`，建议删除 buildSrc，自己在目录下新建一个 buildSrc，把旧 buildSrc 的类拷贝进去。（记得 buildSrc 的包名变动了会影响 apply plugin 的路径），新建 buildSrc 的具体步骤可以见我的博文。https://www.jianshu.com/p/42ce95450adb

**Comment by Mybrc91** [comment]
> > 不能跳转
> 
> 不能跳转说明完全没有找到PathPlugin插件，你可以
> 
> 1. 先检查 PathPlugin 的路径是否正确，是否是`com.feelschaotic.plugin.`
> 2. 路径正常，则先注释掉 `apply plugin: com.feelschaotic.plugin.PathPlugin`
> 3. 重新 clean rebuild 确保编译成功
> 4. 再依次敲入 `apply plugin: com.feelschaotic.plugin.PathPlugin` 留意IDE是否出现键入提示，如图：
> 
> ![](https://user-images.githubusercontent.com/23227460/54605850-344bcf00-4a85-11e9-9107-0be7304e7e5f.png)
> 
> 如果没有出现键入提示，且上面步骤后还是找不到`com.feelschaotic.plugin.PathPlugin`，建议删除 buildSrc，自己在目录下新建一个 buildSrc，把旧 buildSrc 的类拷贝进去。（记得 buildSrc 的包名变动了会影响 apply plugin 的路径），新建 buildSrc 的具体步骤可以见我的博文。https://www.jianshu.com/p/42ce95450adb

不行，插件没反应，只打印log的代码都不生效

**Comment by Mybrc91** [comment]
包名路径写死了“\\”,在linux和unix下路径分隔符是“/”,导致不能正确匹配
